/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as CursosRouteImport } from './routes/cursos'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as AgendarRouteImport } from './routes/agendar'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminRelatoriosRouteImport } from './routes/admin.relatorios'
import { Route as AdminProdutosRouteImport } from './routes/admin.produtos'
import { Route as AdminFuncionariosRouteImport } from './routes/admin.funcionarios'
import { Route as AdminFinanceiroRouteImport } from './routes/admin.financeiro'
import { Route as AdminClientesRouteImport } from './routes/admin.clientes'
import { Route as AdminAgendaRouteImport } from './routes/admin.agenda'

const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const CursosRoute = CursosRouteImport.update({
  id: '/cursos',
  path: '/cursos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendarRoute = AgendarRouteImport.update({
  id: '/agendar',
  path: '/agendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRelatoriosRoute = AdminRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProdutosRoute = AdminProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFuncionariosRoute = AdminFuncionariosRouteImport.update({
  id: '/funcionarios',
  path: '/funcionarios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceiroRoute = AdminFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientesRoute = AdminClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAgendaRoute = AdminAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/agendar': typeof AgendarRoute
  '/contato': typeof ContatoRoute
  '/cursos': typeof CursosRoute
  '/marketplace': typeof MarketplaceRoute
  '/admin/agenda': typeof AdminAgendaRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/funcionarios': typeof AdminFuncionariosRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agendar': typeof AgendarRoute
  '/contato': typeof ContatoRoute
  '/cursos': typeof CursosRoute
  '/marketplace': typeof MarketplaceRoute
  '/admin/agenda': typeof AdminAgendaRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/funcionarios': typeof AdminFuncionariosRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/agendar': typeof AgendarRoute
  '/contato': typeof ContatoRoute
  '/cursos': typeof CursosRoute
  '/marketplace': typeof MarketplaceRoute
  '/admin/agenda': typeof AdminAgendaRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/funcionarios': typeof AdminFuncionariosRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/agendar'
    | '/contato'
    | '/cursos'
    | '/marketplace'
    | '/admin/agenda'
    | '/admin/clientes'
    | '/admin/financeiro'
    | '/admin/funcionarios'
    | '/admin/produtos'
    | '/admin/relatorios'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agendar'
    | '/contato'
    | '/cursos'
    | '/marketplace'
    | '/admin/agenda'
    | '/admin/clientes'
    | '/admin/financeiro'
    | '/admin/funcionarios'
    | '/admin/produtos'
    | '/admin/relatorios'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/agendar'
    | '/contato'
    | '/cursos'
    | '/marketplace'
    | '/admin/agenda'
    | '/admin/clientes'
    | '/admin/financeiro'
    | '/admin/funcionarios'
    | '/admin/produtos'
    | '/admin/relatorios'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AgendarRoute: typeof AgendarRoute
  ContatoRoute: typeof ContatoRoute
  CursosRoute: typeof CursosRoute
  MarketplaceRoute: typeof MarketplaceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cursos': {
      id: '/cursos'
      path: '/cursos'
      fullPath: '/cursos'
      preLoaderRoute: typeof CursosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendar': {
      id: '/agendar'
      path: '/agendar'
      fullPath: '/agendar'
      preLoaderRoute: typeof AgendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/relatorios': {
      id: '/admin/relatorios'
      path: '/relatorios'
      fullPath: '/admin/relatorios'
      preLoaderRoute: typeof AdminRelatoriosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/produtos': {
      id: '/admin/produtos'
      path: '/produtos'
      fullPath: '/admin/produtos'
      preLoaderRoute: typeof AdminProdutosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/funcionarios': {
      id: '/admin/funcionarios'
      path: '/funcionarios'
      fullPath: '/admin/funcionarios'
      preLoaderRoute: typeof AdminFuncionariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/financeiro': {
      id: '/admin/financeiro'
      path: '/financeiro'
      fullPath: '/admin/financeiro'
      preLoaderRoute: typeof AdminFinanceiroRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clientes': {
      id: '/admin/clientes'
      path: '/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AdminClientesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/agenda': {
      id: '/admin/agenda'
      path: '/agenda'
      fullPath: '/admin/agenda'
      preLoaderRoute: typeof AdminAgendaRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAgendaRoute: typeof AdminAgendaRoute
  AdminClientesRoute: typeof AdminClientesRoute
  AdminFinanceiroRoute: typeof AdminFinanceiroRoute
  AdminFuncionariosRoute: typeof AdminFuncionariosRoute
  AdminProdutosRoute: typeof AdminProdutosRoute
  AdminRelatoriosRoute: typeof AdminRelatoriosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAgendaRoute: AdminAgendaRoute,
  AdminClientesRoute: AdminClientesRoute,
  AdminFinanceiroRoute: AdminFinanceiroRoute,
  AdminFuncionariosRoute: AdminFuncionariosRoute,
  AdminProdutosRoute: AdminProdutosRoute,
  AdminRelatoriosRoute: AdminRelatoriosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AgendarRoute: AgendarRoute,
  ContatoRoute: ContatoRoute,
  CursosRoute: CursosRoute,
  MarketplaceRoute: MarketplaceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
